GITHUB_REPO = "DEIN_GITHUB_USERNAME/DEIN_REPO"
GITHUB_BRANCH = "main"
GITHUB_TOKEN = "ghp_xxxxxxxxxxxxxxxxxxxxx"

DATA_DIR = "data_kasse"

BELEG_IP = "192.168.178.95"
OFEN_IP  = "192.168.178.96"
STATUS_TOKEN = "firecake"

# optional – erst später relevant
PUBLIC_API_BASE = ""
